name: Build MinIO (multi-arch image)

on:
  push:
    branches: [ main ]
  schedule:
    # Run every day at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  get-minio-latest:
    name: Get latest MinIO tag
    runs-on: ubuntu-latest
    outputs:
      minio_version: ${{ steps.get_latest.outputs.tag }}
    steps:
      - name: Fetch latest MinIO release
        id: get_latest
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data } = await github.rest.repos.getLatestRelease({
              owner: 'minio',
              repo: 'minio'
            });
            core.setOutput("tag", data.tag_name);

  docker-image:
    name: Build & push Docker image
    needs: [ get-minio-latest ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      # Docker Hub repo (must be lowercase); adjust if you use GHCR instead.
      IMAGE_NAME: ${{ github.repository }}
      MINIO_VERSION: ${{ needs.get-minio-latest.outputs.minio_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute tags
        id: meta
        run: |
          # Docker Hub requires lower-case repo names
          REPO_LC="$(echo "${IMAGE_NAME}" | tr '[:upper:]' '[:lower:]')"
          SHA_SHORT="${GITHUB_SHA::7}"
          TAGS="${REPO_LC}:${SHA_SHORT},${REPO_LC}:${MINIO_VERSION},${REPO_LC}:latest"
          echo "repo_lc=${REPO_LC}" >> "$GITHUB_OUTPUT"
          echo "tags=${TAGS}" >> "$GITHUB_OUTPUT"

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            MINIO_VERSION=${{ env.MINIO_VERSION }}
          platforms: linux/arm/v7,linux/arm64,linux/386,linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ env.MINIO_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
